### ISSUE TITLE
Tratamento de erros em caso de falhas

### ISSUE THREAD

**Issue by cirinho** [remontti/telegramBotShell#1]
Script não verifica se há erro que possa ocorrer ao enviar mensagens ou arquivos. Vamos adicionar algum tratamento de erros ao script para os casos em que a solicitação da API falhar ou o arquivo não puder ser compactado ?

**Comment by cirinho** [comment]
Verificar o status de retorno do curl com ( echo $? ) se for diferente de zero ocorreu um erro para exibir uma mensagem, algo do tipo:

```
# Check curl return status
if [ $? -ne 0 ]; then
  echo "Error sending message"
  exit 1
fi
```

**Comment by cirinho** [comment]
Também pode ser veito verificações de erro para as chamadas de compressão zip e tar também retornarem códigos de status de saída para garantir que a compressão foi bem-sucedida antes de enviar o arquivo. Se falhar pode exibir uma mensagem de erro, por exemplo:

```
# Check compression return status
if [ $? -ne 0 ]; then
  echo "Error compressing file"
  exit 1
fi
```

**Comment by remontti** [comment]
Idéias implementadas do script
